#!/usr/bin/env python3
"""Write the review theme for the ashlar family — and make a painter failure IMPOSSIBLE TO MISS.

The ashlar family is not laid by the theme. The theme places a floor sprite in every walkable cell
and `Tier1AshlarFloor` then paints each one from its stone addresses, because a stone's value
cannot come from anything the tile knows without landing on the tile lattice.

So the theme needs a floor tile that exists and is never meant to be seen. LOOP-PROCESS §4.2 —
**a step that does nothing must go red** — decides what it looks like: it is MAGENTA. If the
painter refuses, or misses a cell, or the manifest fails its cross-check, the floor comes back
screaming instead of coming back plausible. The failure mode this replaces is the dangerous one:
a theme fallback that looks like stone, so a capture of the WRONG floor reviews as the right one.

ONE ROOT, ONE PATTERN — a fact about `TileThemeLoader`, not a preference. It carries a single
`tile_root` and a single `tile_pattern`, so the stub walls are COPIED into the family's directory
under the family's naming scheme, byte for byte, and their sha256 recorded beside the source so
"unchanged" is checkable rather than asserted.

THE WALLS ARE THE TIER-0 STUBS, deliberately. The sighted round's wall set is KNOWN-CULLED — the
device gate returned FAIL on it and §8.3.1 struck the joint grid its tops were built from — so
seating the floor beside it would contaminate any verdict with a wall everyone has already
rejected. Programmer art that announces itself is a better neighbour than a mock that looks like
a proposal.

⚠ WHAT THAT COSTS, STATED RATHER THAN DISCOVERED: §6.5's value stack cannot be read in this
scene. The stack is a relationship between the wall's two planes and the floor, and a stub wall
has no meaningful value. This build can answer *is the floor legible, is it stone, does it read
as made* — it cannot answer *does the floor sit between the planes*.
"""
import argparse
import hashlib
import json
import os
import shutil
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
STUB = os.path.join(REPO, "src/Presentation/assets/tier0_harness/stub")

FALLBACK_ID = 9999
WALL_IDS = list(range(9010, 9035)) + [9040, 9041]


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def export(assets_rel, prefix, theme_name):
    assets = os.path.join(REPO, assets_rel)
    man_path = os.path.join(assets, "MANIFEST.json")
    man = json.load(open(man_path))

    # The unmissable fallback. Magenta at full chroma is outside anything the family can produce —
    # §5.4 reserves warmth and the palette is a narrow grey — so one cell of it is unambiguous.
    fb = np.zeros((32, 32, 3), dtype=np.uint8)
    fb[..., 0] = 255
    fb[..., 2] = 255
    fb[::4, :] = [0, 0, 0]
    Image.fromarray(fb).save(os.path.join(assets, "%s%d.png" % (prefix, FALLBACK_ID)))

    copies = []
    for tid in WALL_IDS:
        s = os.path.join(STUB, "tier0_stub_%d.png" % tid)
        if not os.path.exists(s):
            continue
        d = os.path.join(assets, "%s%d.png" % (prefix, tid))
        shutil.copyfile(s, d)
        copies.append(dict(id=tid, source=os.path.relpath(s, REPO), sha256=sha(d),
                           source_sha256=sha(s)))

    lines = [
        "# GENERATED by tools/tier1_floors/export_theme_ashlar.py — do not hand-edit.",
        "#",
        "# THE FLOOR TILE HERE IS A MAGENTA FALLBACK AND IS NOT THE FAMILY. Every walkable cell",
        "# is repainted by Tier1AshlarFloor from that cell's stone addresses; this entry exists",
        "# only so a sprite is present to repaint. Magenta on purpose (LOOP-PROCESS §4.2): if the",
        "# painter refuses or misses a cell, the floor comes back screaming rather than plausible.",
        "#",
        "# The walls are the tier-0 programmer-art stubs, copied byte for byte. They are mocks and",
        "# are out of scope for the floor gate.",
        'tile_root: "res://%s"' % assets_rel,
        'tile_pattern: "%s{id}.png"' % prefix,
        "",
        "themes:",
        "  boundary:",
    ]
    for role in ("floor_primary", "floor_accent", "floor_dark", "floor_interior", "floor_worn"):
        lines.append("    %s: [%d]" % (role, FALLBACK_ID))
    lines.append("    wall_autotile:")
    for k in range(16):
        lines.append("      %d: %d" % (k, 9010 + k))
    lines.append("    wall_diagonal:")
    for k, v in (("corner_outer_nw", 9030), ("corner_outer_ne", 9031),
                 ("corner_outer_sw", 9032), ("corner_outer_se", 9033), ("interior_fill", 9034)):
        lines.append("      %s: %d" % (k, v))
    lines.append("    stair_down: [9040]")
    lines.append("    stair_up: [9041]")
    lines += ["", "default_theme: boundary", ""]

    tp = os.path.join(assets, theme_name)
    open(tp, "w").write("\n".join(lines))
    man["theme"] = theme_name
    man["fallback_tile"] = dict(id=FALLBACK_ID, why="magenta; a painter failure must go red")
    man["wall_mocks"] = copies
    json.dump(man, open(man_path, "w"), indent=1)
    print("  %-38s theme=%s  walls copied=%d" % (assets_rel, theme_name, len(copies)))
    return tp


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--plant", action="store_true", help="also export the §4 plant's theme")
    a = ap.parse_args()
    print("ASHLAR REVIEW THEMES")
    export("src/Presentation/assets/tier1_ashlar", "tier1_ashlar_",
           "tile_themes_tier1_ashlar.yaml")
    if a.plant:
        export("src/Presentation/assets/tier1_ashlar_plant", "tier1_ashlarp_",
               "tile_themes_tier1_ashlar_plant.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
