#!/usr/bin/env python3
"""Write the tier-one review theme, and bring the WALL MOCKS along unchanged.

WHY THE WALLS ARE THE TIER-0 STUBS AND NOT THE SIGHTED ROUND'S
--------------------------------------------------------------
This session's gate is about FLOORS and the §6.2.1 rig. The walls in the scene are there to make
the scene a scene, and the brief says so: *"walls remain the existing mocks, labelled as such."*

The choice of WHICH mock is not arbitrary, because the alternative is worse than useless. The
sighted round's wall set is not a neutral placeholder — it is a **known-culled** construction:
Rafe's device gate returned FAIL on it, and §8.3.1 then ruled out the joint grid its wall tops
were built from. Putting it in this scene would seat the floor family beside art the bible has
already struck, and any verdict on the floors would be contaminated by a wall everybody has
already said no to.

`make_stub_tiles.py`'s programmer art is the honest choice precisely because nobody could mistake
it for a candidate. Its own README calls it *"Obviously-fake programmer-art fixtures. Not art,
not a palette."* A mock that announces itself is a better neighbour than a mock that looks like a
proposal.

⚠ WHAT THAT COSTS, STATED RATHER THAN DISCOVERED: **§6.5's value stack cannot be read in this
scene.** The stack is a relationship between the wall's two planes and the floor, and a stub
wall has no meaningful value. So this build can answer *is the floor family legible, and does the
rig make it legible across the lit radius* — and it cannot answer *does the floor sit between the
planes*. The floor's own measured albedo is written into the manifest so the wall round that
comes next can derive its two planes from a floor that actually exists, which is the right order
and the one §6.5 was denied when it had to invent the floor.

ONE ROOT, ONE PATTERN — a fact about the loader, not a preference. `TileThemeLoader` carries a
single `tile_root` and a single `tile_pattern` for the whole config, so every tile a theme names
must live in one directory under one naming scheme. The stub walls are therefore COPIED into the
tier-one asset directory under the tier-one name, byte for byte, and recorded in the manifest as
copies. Nothing about them is altered; the sha256 of each copy is written beside its source so
the claim "unchanged" is checkable rather than asserted.
"""
import hashlib
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import field_laws as FL      # noqa: E402

ASSETS_REL = "src/Presentation/assets/tier1_floors"
ASSETS = os.path.join(REPO, ASSETS_REL)
STUB = os.path.join(REPO, "src/Presentation/assets/tier0_harness/stub")
THEME = os.path.join(ASSETS, "tile_themes_tier1_floors.yaml")

# The stub roles this theme borrows, verbatim from tile_themes_stub.yaml.
WALL_AUTOTILE = {i: 9010 + i for i in range(16)}
WALL_DIAGONAL = dict(corner_outer_nw=9030, corner_outer_ne=9031,
                     corner_outer_sw=9032, corner_outer_se=9033, interior_fill=9034)
STAIRS = dict(stair_down=9040, stair_up=9041)


def main():
    man = json.load(open(os.path.join(ASSETS, "MANIFEST.json")))
    floor_ids = [o["id"] for o in man["oriented"]]
    if not floor_ids:
        raise SystemExit("REFUSING: the manifest names no oriented floor tiles.")

    copied = []
    for tid in list(WALL_AUTOTILE.values()) + list(WALL_DIAGONAL.values()) + list(STAIRS.values()):
        src = os.path.join(STUB, "tier0_stub_%d.png" % tid)
        if not os.path.exists(src):
            raise SystemExit("REFUSING: wall mock %s is missing. A theme naming a tile that is "
                             "not there renders a hole, and a hole in the scene is not a mock." % src)
        dst = os.path.join(ASSETS, "tier1_floor_%d.png" % tid)
        shutil.copyfile(src, dst)
        a, b = FL.sha256_file(src), FL.sha256_file(dst)
        if a != b:
            raise SystemExit("REFUSING: copy of %s does not match its source." % src)
        copied.append(dict(id=tid, source=os.path.relpath(src, REPO),
                           file=os.path.basename(dst), sha256=a, role="wall mock, unchanged"))

    lines = [
        "# GENERATED by tools/tier1_floors/export_theme.py — do not hand-edit.",
        "#",
        "# TIER ONE, SESSION ONE — the Boundary floor family in the review scene.",
        "#",
        "# floor_* roles  REAL CANDIDATE ART. 3 base material tiles (ART-BIBLE-v0 §8.3: material",
        "#                only, no incident) x 8 orientations of the square = 24 ids, distributed",
        "#                by TileThemeConfig.PickVariant's position hash. Every one screened CLEAN",
        "#                by tools/tier1_floors/field_laws.py, whose controls are in",
        "#                tools/tier1_floors/controls/CONTROLS.json.",
        "#",
        "# wall_* roles   MOCKS. Byte-for-byte copies of the tier-0 programmer-art stubs, which",
        "#                that harness's own README calls 'obviously-fake programmer-art fixtures.",
        "#                Not art, not a palette.' They are NOT candidates and are not judged.",
        "#                §6.5's value stack cannot be read against them — see this file's",
        "#                generator for why that is stated rather than worked around.",
        "#",
        "# THE INCIDENT AND CHANNEL OVERLAYS ARE NOT IN THIS FILE. They are not a tile role: a",
        "# cell may carry none, one or two of them, chosen per instance, and TileThemeLoader's",
        "# schema has no shape for that. They live in MANIFEST.json and are placed by",
        "# FloorIncidentPlanner. §8.3: a tile is the material, the incident is the variant.",
        "",
        'tile_root: "res://%s"' % ASSETS_REL,
        'tile_pattern: "tier1_floor_{id}.png"',
        "",
        "themes:",
        "  boundary:",
    ]
    ids = "[" + ", ".join(str(i) for i in floor_ids) + "]"
    # Every floor role gets the same family: this session authored ONE material, and inventing a
    # different-looking accent or worn tile to fill a role would be shipping art nobody asked
    # for. FloorComposer's Dark role still applies its shadow modulate on top.
    for role in ("floor_primary", "floor_accent", "floor_dark", "floor_interior", "floor_worn"):
        lines.append("    %s: %s" % (role, ids))
    lines.append("    wall_autotile:")
    for k in sorted(WALL_AUTOTILE):
        lines.append("      %d: %d" % (k, WALL_AUTOTILE[k]))
    lines.append("    wall_diagonal:")
    for k, v in WALL_DIAGONAL.items():
        lines.append("      %s: %d" % (k, v))
    for k, v in STAIRS.items():
        lines.append("    %s: [%d]" % (k, v))
    lines += ["", "default_theme: boundary", ""]

    with open(THEME, "w") as f:
        f.write("\n".join(lines))

    man["wall_mocks"] = copied
    man["theme"] = os.path.relpath(THEME, REPO)
    with open(os.path.join(ASSETS, "MANIFEST.json"), "w") as f:
        json.dump(man, f, indent=1)

    print("theme written: %s" % os.path.relpath(THEME, REPO))
    print("  floor ids (real art):   %d  (%d..%d)" % (len(floor_ids), min(floor_ids), max(floor_ids)))
    print("  wall/stair ids (mocks): %d, copied unchanged from the tier-0 stub set" % len(copied))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
