#!/usr/bin/env python3
"""THE PHOTOMETRIC PROBE — measure the rig's transfer before authoring a single wall pixel.

WHAT IT IS FOR
--------------
Bible section 6.2 (COUPLING FLAG): *"the engine compresses the authored value ratio ... authored
ratios are derived backwards from delivered targets on the current rig"*, and section 6.2.1's
ruling records the one thing the rig pass could not answer: *"The section 6.5 stack surviving the
falloff across the lit radius - NOT ANSWERED, and it could not be ... owed by the first round
that puts real walls in the scene."*

That re-derivation needs one quantity and only one: **the lighting multiplier L at each place a
plane sits**. Godot's 2D lighting is multiplicative in albedo, so for any two samples

    delivered_A / delivered_B  =  (authored_A / authored_B) * (L_A / L_B)

and every compression factor in the wall recipe is an L-ratio between two positions. The wall
face sits half a tile SOUTH of its own top, and the player carries the lamp, so the face is
always nearer the light than the plane above it - which is the whole of the 1.48x the sighted
round measured, and it is geometry, not art.

So this probe paints the ENTIRE SCENE one flat albedo and captures it. The capture is then a
picture of L, sampled everywhere the scene has geometry, at the ratified rig.

THE POSITIVE CONTROLS (section 13.5 / LOOP-PROCESS section 4) — three, and each can fail:

  LINEARITY   the same scene at a second albedo must scale by the albedo ratio at every sample.
              If the pipeline were doing sRGB<->linear conversion anywhere, or clamping, the
              ratio would bend and every number derived here would be wrong.
  UNITY       at light energy 0 the face/top ratio must be EXACTLY 1.000 - ambient is a
              CanvasModulate and multiplies both planes identically. A compression measured
              under ambient alone would be an artefact of the sampler, not of the rig.
  DARK-CELL   DungeonRenderer multiplies wall-adjacent floor cells by DarkFloorModulate. The
              probe must see that constant and report it, because a floor sample taken beside a
              wall is 8% dark for a reason that has nothing to do with light.
"""
import argparse
import json
import os
import subprocess
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
ASSETS_REL = "src/Presentation/assets/tier1_walls_probe"
ASSETS = os.path.join(REPO, ASSETS_REL)
T = 32

# A distinct id block so a probe fixture can never be mistaken for, or collide with, a candidate.
FLAT_ID = 9700          # the uniform albedo, all roles
SPLIT_TOP = 9710        # a two-plane fixture: top band one value, face another
SPLIT_FACE = 9711


def flat_tile(v):
    return np.full((T, T, 3), v, dtype=np.uint8)


def write(path, arr):
    Image.fromarray(arr, "RGB").save(path)


def emit(albedo):
    os.makedirs(ASSETS, exist_ok=True)
    ids = {}
    a = flat_tile(albedo)
    p = os.path.join(ASSETS, "probe_%d.png" % FLAT_ID)
    write(p, a)
    ids["flat"] = FLAT_ID

    theme = [
        "# GENERATED by tools/tier1_walls/make_photometric_probe.py - a MEASURING FIXTURE.",
        "#",
        "# Every role points at ONE flat tile of albedo %d. Nothing here is art, nothing here is" % albedo,
        "# a palette proposal, and nothing here lands. The capture it produces is a picture of the",
        "# rig's lighting multiplier L, which is the quantity bible section 6.2's coupling flag",
        "# says every authored wall ratio has to be solved backwards through.",
        'tile_root: "res://%s"' % ASSETS_REL,
        'tile_pattern: "probe_{id}.png"',
        "",
        "themes:",
        "  boundary:",
        "    floor_primary: [%d]" % FLAT_ID,
        "    floor_accent: [%d]" % FLAT_ID,
        "    floor_dark: [%d]" % FLAT_ID,
        "    floor_interior: [%d]" % FLAT_ID,
        "    floor_worn: [%d]" % FLAT_ID,
        "    wall_autotile:",
    ]
    for m in range(16):
        theme.append("      %d: %d" % (m, FLAT_ID))
    theme += [
        "    wall_diagonal:",
        "      corner_outer_nw: %d" % FLAT_ID,
        "      corner_outer_ne: %d" % FLAT_ID,
        "      corner_outer_sw: %d" % FLAT_ID,
        "      corner_outer_se: %d" % FLAT_ID,
        "      interior_fill: %d" % FLAT_ID,
        "    stair_down: [%d]" % FLAT_ID,
        "    stair_up: [%d]" % FLAT_ID,
        "",
        "default_theme: boundary",
        "",
    ]
    tp = os.path.join(ASSETS, "tile_themes_probe.yaml")
    open(tp, "w").write("\n".join(theme))
    return ids, tp


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--albedo", type=int, default=101)
    a = ap.parse_args()
    ids, tp = emit(a.albedo)
    print("probe albedo=%d  ->  %s" % (a.albedo, os.path.relpath(tp, REPO)))
